# Generated by Django 3.2.5 on 2021-07-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=30)),
                ('m_manufacuter_city', models.CharField(max_length=20)),
                ('m_price', models.IntegerField()),
                ('m_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacies')),
            ],
        ),
    ]
