# Generated by Django 3.2.5 on 2021-07-17 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210707_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='m_pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_set', to='api.pharmacy'),
        ),
    ]
