# Generated by Django 3.2.5 on 2021-07-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medications',
            new_name='Medication',
        ),
        migrations.RenameModel(
            old_name='Pharmacies',
            new_name='Pharmacy',
        ),
    ]
